
name: QuizStation
description: multiple choice quiz app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  google_fonts: ^5.0.0
  flutter_svg: ^1.1.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/bg_arcade.png
    - assets/images/logo.png
    - assets/icons/trophy.png
